[theme]
base                     = "light"
backgroundColor          = "#000000"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1A1A2E"
primaryColor             = "#378ADD"
font                     = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
